name: sat-scheduler
channels:
  - conda-forge
dependencies:
  - numpy
  - pyyaml
  - astropy
  - isodate
  - orekit=11.2
  - shapely
  - pip
  - geopandas
  - folium
  - python=3.10.4
  # dev dependencies
  - pytest
  - pytest-cov
  - black
  - flake8
