name: sat-scheduler
channels:
  - defaults
  - conda-forge
dependencies:
  - requests
  - orekit=11.2
  - shapely
  - yaml
  - pyyaml
  - astropy
  - isodate
  - pip:
      - alphashape==1.3.1
      - fiona==1.8.21
      - folium=0.12.1.post1
      - geopandas=0.10.2
      