name: sat-scheduler
channels:
  - conda-forge
dependencies:
  - astropy
  - dacite
  - isodate
  - geopandas
  - numpy
  - pip
  - python
  - orekit>=11.2
  - pyyaml
  - shapely
  - czml3
  
  # dev dependencies
  - black
  - build
  - flake8
  - flake8-docstrings
  - pep517
  - pytest
  - pytest-cov
  - pip:
    - py-rebar>=0.2.0
    - orekit-factory>=0.2.0
    - ortools
    - stactools

