name: sat-scheduler
channels:
  - conda-forge
dependencies:
  - astropy
  - isodate
  - geopandas
  - numpy
  - pip
  - python
  - orekit>=11.2
  - pyyaml
  - shapely
  - czml3
  
  # dev dependencies
  - pytest
  - pytest-cov
  - black
  - flake8
  - pip:
    # TODO: versions here
    - stactools
    - git+https://github.com/greyskyy/py-rebar.git
    - git+https://github.com/greyskyy/orekit-factory.git
