name: sat-scheduler
channels:
  - conda-forge
  - defaults
dependencies:
#  - requests=2.27.1
  - orekit=11.2
  - shapely=1.7.0
#  - yaml=0.2.5
  - pip=21.2.4
#  - astropy=5.0.4
#  - isodate=0.6.0
  - geopandas=0.10.2
  - folium=0.12.1.post1
  - python=3.10.4
  - pip:
#      - alphashape==1.3.1
#      - fiona==1.8.21
#      - folium==0.12.1.post1
      - pyyaml==6.0
