"""Satellite models."""
import astropy.units as u
import itertools
import orekitfactory.time
import typing

from org.orekit.attitudes import AttitudeProvider
from org.orekit.data import DataContext
from org.orekit.frames import Frame
from org.orekit.models.earth import ReferenceEllipsoid
from org.orekit.orbits import Orbit
from org.orekit.propagation import Propagator
from org.orekit.propagation.events import EventDetector
from org.orekit.propagation.analytical.tle import TLE

from ..configuration import get_config, SatelliteData, PropagatorConfiguration, Configuration
from ..configuration.units import Mass
from .sensor import SensorModel, construct_sensor_model
from ..utils import (
    get_reference_ellipsoid,
    build_propagator,
    build_orbit,
    build_attitude_provider,
    build_orbit_event_handler,
    OrbitEvent,
)


class SatelliteModel:
    """A single satellite model."""

    def __init__(
        self,
        id: str,
        data: SatelliteData,
        orbit: Orbit | TLE,
        orbit_frame: Frame,
        propagator: Propagator,
        sensors: typing.Sequence[SensorModel],
        attitudes: typing.Dict[str, AttitudeProvider],
        default_attitude_law: str,
        mass: Mass = None,
        event_detector: EventDetector = None,
        event_list_supplier: typing.Callable[[], list[OrbitEvent]] = None,
    ):
        """Class constructor.

        Args:
            id (str): Satellite id.
            data (SatelliteData): Satellite data.
            orbit (Orbit | TLE): Orbit definition.
            orbit_frame (Frame): Local orbit frame.
            propagator (Propagator): Satellite propagator
            sensors (typing.Sequence[SensorModel]): Satellite sensor models.
            attitudes (typing.Dict[str, AttitudeProvider]): Sattelite attitude providers, indexed by mode name.
            default_attitude_law (str): Name of the default attitude law.
            mass (Mass, optional): Satellite mass. If None, the mass will be used from the data. Defaults to None.
            event_detector (EventDetector, optional): Orbit event detector triggering at orbit rev crossings. Defaults
            to None.
            event_list_supplier (typing.Callable[[], list[OrbitEvent]], optional): Callable taking no arguments and
            returning a list of detected orbit events. Defaults to None.
        """
        self.__id = id
        self.__data = data
        self.__orbit = orbit
        self.__orbit_frame = orbit_frame
        self.__propagator = propagator
        self.__sensors = tuple(sensors)
        self.__attitudes = attitudes
        self.__defaultAtLaw = default_attitude_law
        self.__mass = mass or data.mass
        self.__event_detector = event_detector
        self.__event_detector_registered = False
        self.__event_list_supplier = event_list_supplier

    @property
    def id(self) -> str:
        """The satellite's id."""
        return self.__id

    @property
    def data(self) -> SatelliteData:
        """The satellite data."""
        return self.__data

    @property
    def name(self) -> str:
        """The long name of the satellite."""
        return self.data.name if self.data.name else self.__id

    @property
    def mass(self) -> u.Quantity:
        """The satellite's mass."""
        return self.__mass

    @property
    def inertial_frame(self) -> Frame:
        """The inertial frame of this satellite, used in propagation."""
        return self.propagator.getFrame()

    @property
    def propagator(self) -> Propagator:
        """The satellite propagator."""
        return self.__propagator

    @property
    def sensors(self) -> tuple[SensorModel]:
        """The list of sensors on this satellite platform."""
        return self.__sensors

    @property
    def orbit(self) -> TLE | Orbit:
        """The satellite's orbit definition."""
        return self.__orbit

    @property
    def orbit_frame(self) -> Frame:
        """The local orbit frame."""
        self.__orbit_frame

    @property
    def event_generation(self) -> bool:
        """Indicate if orbit event generation is enabled."""
        return self.__event_detector_registered

    @property
    def events_generated(self) -> bool:
        """Indicate whether any orbit events have been generated by the propagator."""
        return True if self.event_list else False

    @property
    def event_list(self) -> tuple[OrbitEvent]:
        """The list of generated orbit events."""
        return tuple(self.__event_list_supplier())

    def enable_event_generation(self):
        """Enable ephemeris event generation during propagation."""
        if self.__event_detector and not self.__event_detector_registered:
            self.propagator.addEventDetector(self.__event_detector)
            self.__event_detector_registered = True

    def construct_rev_intervals(
        self, bounding_interval: orekitfactory.time.DateInterval = None
    ) -> tuple[orekitfactory.time.DateInterval]:
        """Create rev boundary intervals from generated events.

        If the `bounding_interval` is specified, the resulting list will include an interval that ends at the first
        orbit rev crossing event and another that begins at the last orbit rev crossing event. If not specified,
        the resulting list will only contain intervals between computed rev events.

        Args:
            bounding_interval (orekitfactory.time.DateInterval, optional): The bounding interval within which rev
            intervals will be computed. Defaults to None.

        Returns:
            tuple[orekitfactory.time.DateInterval]: The resulting rev intervals.
        """
        if bounding_interval:
            bounding_interval = orekitfactory.time.as_dateinterval(bounding_interval)

        if self.events_generated:
            times = [e.date for e in self.event_list if e.event == self.data.rev_boundary]

            if bounding_interval.start.isBefore(times[0]):
                times.insert(0, bounding_interval.start)
            if bounding_interval.stop.isAfter(times[-1]):
                times.append(bounding_interval.stop)

            return tuple(orekitfactory.time.DateInterval(t0, t1) for t0, t1 in itertools.pairwise(times))
        elif bounding_interval:
            return tuple(bounding_interval)
        else:
            return None

    def sensor(self, id: str) -> SensorModel:
        """Locate the sensor with the defined id.

        Args:
            id (str): The sensor id.

        Returns:
            SensorModel: the sensor, or None if no sensor matches the id.
        """
        for s in self.__sensors:
            if s.id == id:
                return s

        return None

    def getAttitudeProvider(self, name: str = None) -> AttitudeProvider:
        """Get the attitude provider for the specifed mode.

        Args:
            name (str, optional): The attitude mode name. Defaults to None.

        Returns:
            AttitudeProvider: The provider for the specified attitude mode
        """
        if name is None:
            return self.__attitudes[self.__defaultAtLaw]

        return self.__attitudes[name]

    def __str__(self) -> str:
        """Represent this model as a string.

        Returns:
            str: The string summary for this object.
        """
        return f"Satellite[id={self.id},sensors=[" + ",".join([s.id for s in self.__sensors]) + "]]"


def construct_satellite_model(
    id: str, data: SatelliteData, context: DataContext = None, earth: ReferenceEllipsoid = None
) -> SatelliteModel:
    """Construct a SatelliteModel instance.

    This method builds the necessary data objects and provides them to the `SatelliteModel` constructor.

    Args:
        id (str): The unique satellite id.
        data (SatelliteData): The backing data for this model.
        context (DataContext, optional): The data context to use while building the model. If None, the default
        context will be used. Defaults to None.
        earth (ReferenceEllipsoid, optional): The reference ellipsoid to use when building the propagator. The
        WGS-84 ellipsoid will be used if None. Defaults to None.

    Returns:
        SatelliteModel: The contructed satellite model.
    """
    # set the context
    if context is None:
        context = DataContext.getDefault()

    # built earth reference
    if earth is None:
        earth = get_reference_ellipsoid(context=context)

    # build propagator configuration
    config = get_config()
    propagator_config: PropagatorConfiguration = PropagatorConfiguration.union(config.propagator, data.propagator)

    # build the orbit and the orbit frame
    orbit = build_orbit(data, context)
    orbit_frame: Frame = orbit.getFrame() if isinstance(orbit, Orbit) else context.getFrames().getTEME()

    # initialize the attitudes, get the mission attitude provider
    attitudes = {}
    defaultAtLaw = None
    atProv = None
    if data.attitudes:
        for item in data.attitudes:
            attitudes[item.name] = build_attitude_provider(data, item, orbit_frame)
            if item.default:
                defaultAtLaw = item.name

        if defaultAtLaw is None and attitudes:
            defaultAtLaw = list(attitudes.keys())[0]

        atProv = attitudes["mission"]

    # build the propagator
    mass = data.mass or Mass("100 kg")
    propagator = build_propagator(
        orbit,
        config=propagator_config,
        mass=mass,
        context=context,
        attitudeProvider=atProv,
        centralBody=earth,
    )

    if data.rev_boundary:
        detector, event_list = build_orbit_event_handler(data.rev_boundary, context=context, body=earth)
    else:
        detector = None
        event_list = None

    # build the sensor models
    sensors = (construct_sensor_model(d) for d in data.sensors)

    return SatelliteModel(
        id=id,
        data=data,
        orbit=orbit,
        orbit_frame=orbit_frame,
        sensors=sensors,
        attitudes=attitudes,
        propagator=propagator,
        default_attitude_law=defaultAtLaw,
        mass=mass,
        event_detector=detector,
        event_list_supplier=event_list,
    )


def load_satellite_models(
    config: Configuration = None, context: DataContext = None, earth: ReferenceEllipsoid = None
) -> tuple[SatelliteModel]:
    """Load satellite models from the application configuration.

    Args:
        config (Configuration, optional): The application cofiguration. The global config will be retrieved
        if None. Defaults to None.
        context (DataContext, optional): The data context to use during construction. If None, the default
        context will be used. Defaults to None.
        earth (ReferenceEllipsoid, optional): The earth ellipsoid to use. If None, WGS-84 will be used. Defaults
        to None.

    Returns:
        tuple[SatelliteModel]: List of satellite models loaded from the configuration.
    """
    if config is None:
        config = get_config()

    return tuple(
        construct_satellite_model(id, data, context=context, earth=earth)
        for id, data in config.satellites.items()
        if not data.filter
    )
